In [3]:
import numpy as np
import matplotlib.pyplot as plt
from public_tests import *
from utils import *


In [5]:
X_train = np.array([[1,1,1],[1,0,1],[1,0,0],[1,0,0],[1,1,1],[0,1,1],[0,0,0],[1,0,1],[0,1,0],[1,0,0]])
y_train = np.array([1,1,0,0,1,0,0,1,1,0])

In [10]:
print(X_train[:5])
print(type(X_train))

[[1 1 1]
 [1 0 1]
 [1 0 0]
 [1 0 0]
 [1 1 1]]
<class 'numpy.ndarray'>


In [11]:
print("shape X: ", X_train.shape)
print("shape y: ", y_train.shape)
print("m:" , len(X_train))

shape X:  (10, 3)
shape y:  (10,)
m: 10


In [12]:
#Calculate entropy

In [18]:
def compute_entropy(y):
    m = len(y)
    

    if m == 0:
        return 0.0
        
    p1 = np.sum(y) / m
    

    if p1 == 0 or p1 == 1:
        return 0.0
        
    entropy = -p1 * np.log2(p1) - (1 - p1) * np.log2(1 - p1)
    
    return entropy


In [20]:

print("Entropy at root node: ", compute_entropy(y_train)) 

# UNIT TESTS
compute_entropy_test(compute_entropy)

Entropy at root node:  1.0
 All tests passed. 
